name: Build and Release Resume

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Resume
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run build.sh
        run: make

      - name: Check for resume.pdf
        run: |
          if [ ! -f resume.pdf ]; then
            echo "resume.pdf not found!"
            cat resume.log
            exit 1
          fi

      - name: Delete GitHub Release
        id: delete_release
        uses: liudonghua123/delete-release-action@v1
        with:
          release_name: "latest"

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: "latest"
          draft: false
          prerelease: false

      - name: Upload resume.pdf to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./resume.pdf
          asset_name: resume.pdf
          asset_content_type: application/pdf
